name: xl_bot
description: "A new Flutter project."
version: 0.0.1
homepage: ""

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.3
  http: ^1.6.0
  google_fonts: ^6.3.2
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0